"""empty message

Revision ID: 0a0533d1f8bc
Revises: 190b7c3e953c
Create Date: 2025-06-17 16:24:42.657488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0533d1f8bc'
down_revision = '190b7c3e953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_favorite_pkey'),
    sa.UniqueConstraint('user_id', name='user_favorite_user_id_key')
    )
    # ### end Alembic commands ###
