"""empty message

Revision ID: 190b7c3e953c
Revises: f560fdd9c01a
Create Date: 2025-06-17 16:02:27.209367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190b7c3e953c'
down_revision = 'f560fdd9c01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite')
    # ### end Alembic commands ###
